"use client";

import { FormEvent, use, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ApiResponse, EMPTY_ROLE_FORM, Role, RoleForm } from "../../types";

const API_URL = "http://localhost:3001/roles";
type FormErrors = Partial<Record<keyof RoleForm, string>>;
export default function EditRolePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const router = useRouter();
  const [form, setForm] = useState<RoleForm>(EMPTY_ROLE_FORM); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [errors, setErrors] = useState<FormErrors>({}); const [serverError, setServerError] = useState("");
  useEffect(() => { fetch(`${API_URL}/${id}`).then(async (response) => { const json: ApiResponse<Role> = await response.json(); if (!response.ok) throw new Error(json.message || "Role tidak ditemukan."); setForm({ nama_role: json.data.nama_role ?? "", deskripsi: json.data.deskripsi ?? "" }); }).catch((reason) => setServerError(reason instanceof Error ? reason.message : "Tidak bisa memuat role.")).finally(() => setLoading(false)); }, [id]);
  const handleSubmit = async (event: FormEvent) => { event.preventDefault(); const nextErrors: FormErrors = {}; if (!form.nama_role.trim()) nextErrors.nama_role = "Nama role wajib diisi."; if (!form.deskripsi.trim()) nextErrors.deskripsi = "Deskripsi wajib diisi."; if (Object.keys(nextErrors).length) { setErrors(nextErrors); return; } setSaving(true); setServerError(""); try { const response = await fetch(`${API_URL}/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nama_role: form.nama_role.trim(), deskripsi: form.deskripsi.trim() }) }); const json: ApiResponse<unknown> = await response.json(); if (!response.ok) throw new Error(json.message || "Gagal memperbarui role."); router.push(`/dashboard/roles/${id}`); } catch (error) { setServerError(error instanceof Error ? error.message : "Tidak bisa terhubung ke server."); } finally { setSaving(false); } };
  if (loading) return <div className="text-sm" style={{ color: "var(--color-text-muted)" }}>Memuat role...</div>;
  return <div className="max-w-2xl"><div className="flex items-center gap-2 text-sm mb-6" style={{ color: "var(--color-text-muted)" }}><Link href="/dashboard/roles" style={{ color: "var(--color-primary)" }}>Roles</Link><span>›</span><span>Edit Role</span></div><h1 className="text-2xl font-bold mb-1">Edit Role</h1><p className="text-sm mb-6" style={{ color: "var(--color-text-muted)" }}>Perbarui informasi role.</p>{serverError && <div className="mb-5 p-3 rounded-lg text-sm" style={{ background: "var(--color-danger-pale)", color: "var(--color-danger)" }}>{serverError}</div>}<div className="card p-6"><form onSubmit={handleSubmit} className="space-y-5" noValidate><div><label className="block text-sm font-medium mb-1.5">Nama Role</label><input className={`input-base ${errors.nama_role ? "error" : ""}`} value={form.nama_role} onChange={(event) => setForm((current) => ({ ...current, nama_role: event.target.value }))} />{errors.nama_role && <p className="mt-1 text-xs" style={{ color: "var(--color-danger)" }}>{errors.nama_role}</p>}</div><div><label className="block text-sm font-medium mb-1.5">Deskripsi</label><textarea className={`input-base min-h-28 ${errors.deskripsi ? "error" : ""}`} value={form.deskripsi} onChange={(event) => setForm((current) => ({ ...current, deskripsi: event.target.value }))} />{errors.deskripsi && <p className="mt-1 text-xs" style={{ color: "var(--color-danger)" }}>{errors.deskripsi}</p>}</div><div className="flex gap-3 pt-2"><Link href={`/dashboard/roles/${id}`} className="btn-secondary flex-1 justify-center">Batal</Link><button type="submit" className="btn-primary flex-1 justify-center" disabled={saving}>{saving ? "Menyimpan..." : "Simpan Perubahan"}</button></div></form></div></div>;
}